### ISSUE TITLE
Video in list opens image of video when played

### ISSUE THREAD

**Issue by VitoMinheere** [TimeTraveller-San/yTermPlayer#15]
Multiple songs in my playlist open an image of the video when played. 

[Playlist](https://www.youtube.com/playlist?list=PL__TjrzvyO2qsozVY4mk-KHWGiGY5NjdS)

Song titles with this issue:
Hydro & War - Jam [Horizons]
Nucleus & Paradox - No Spaced Place

![pic-full-190903-2140-51](https://user-images.githubusercontent.com/10959946/64203362-89449b80-ce93-11e9-92b0-bdb7b0a678ea.png)
The image pops up in the current workspace(i3) and cannot be closed unless yterm is also closed. The image closes when the next track is selected.

**Comment by VitoMinheere** [comment]
I found a solution the [Python-mpv](https://github.com/jaseg/python-mpv) repo

[Issue #81](https://github.com/jaseg/python-mpv/issues/81) mentions adding video=False to mpv.MPV() to explcitly not load a video.

See pull request #16

**Comment by vaibkumr** [comment]
Amazing! Thank you very much for your contribution :)
