### ISSUE TITLE
Hello, i having an issues

### ISSUE THREAD

**Issue by Lzmog** [TimeTraveller-San/yTermPlayer#2]
**duck@duck:~/Downloads/yTermPlayer/yTermPlayer$** python __main__.py
Traceback (most recent call last):
  File "__main__.py", line 11, in <module>
    from .music_api import YoutubePlayer
ValueError: Attempted relative import in non-package

Could you help me to solve it?

**Comment by vaibkumr** [comment]
You need to install the package from pypi through: `pip install ytermplayer`
if you're trying to run without installing the package, just change all the relative import statements as follows `from .music_api import YoutubePlayer` to  `from music_api import YoutubePlayer`
remove the "." before every import statement in all the files. That should do it.
Let me know if that helps.
