### ISSUE TITLE
HTTP is not supported , Couldn't fetch this song 

### ISSUE THREAD

**Issue by Maru-Yasa** [TimeTraveller-San/yTermPlayer#21]
run on Kali Linux, i got HTTP is not supported error when playing a music,

**Comment by vaibkumr** [comment]
Hey,

yTermPlayer can be used only for playing youtube playlists, not individual songs. 
Please paste URLs of the format `https://www.youtube.com/playlist?list=<PLAYLIST_CODE>`. Unfortunately, if you want to play a single song you will need to add it in a playlist (through the browser) and then play it. If you still want to do this on the terminal, please see more mature projects like [mps-youtube](https://github.com/mps-youtube/mps-youtube).
